language: ruby
rvm:
  - ruby
  - ruby-2.2
  - rubinius-3.86
# Problem with rbconfig/sizeof
#  - jruby
install: gem install minitest simplecov
script: rake test
sudo: required # for rubinius-3.86 container update