language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - ruby
  - rubinius-3.86
  - jruby
install: gem install minitest simplecov
script: rake test
sudo: required # for rubinius-3.86 container update